insert into public.issues (
  id,
  title,
  body,
  community,
  category,
  author,
  state,
  upvotes,
  downvotes,
  comment_count,
  supporter_count,
  consensus_score,
  opposing_view_support,
  cluster_mix,
  counter_cluster,
  counter_author,
  counter_summary,
  urgency_label
) values
(
  'issue-1',
  'Should cities publish monthly rent dashboards before approving major rezoning plans?',
  'People in fast-growth neighborhoods want more housing, but they also want a public record of whether promised affordability gains are actually happening. A transparent dashboard could make zoning debates less abstract and easier to track over time.',
  'r/housingpolicy',
  'Economy',
  'Maya',
  'California',
  184,
  41,
  2,
  412,
  91,
  68,
  '[{"cluster":"Civic Reformers","support":29},{"cluster":"Pragmatic Moderates","support":27},{"cluster":"Institutional Skeptics","support":24},{"cluster":"Local Organizers","support":20}]'::jsonb,
  'Institutional Skeptics',
  'Rowan',
  'Public dashboards help, but if cities rush the metric design they can create a false sense of progress. The stronger move may be tying publication requirements to enforcement and tenant remedy timelines.',
  'High urgency'
),
(
  'issue-2',
  'Would a nationwide preventive care credit reduce emergency room overload?',
  'Supporters argue that covering screenings and routine care earlier would cut downstream costs and make care feel more accessible. Critics want more evidence on how it would be funded and whether rural providers could absorb the demand.',
  'r/publichealth',
  'Healthcare',
  'Jonah',
  'Michigan',
  132,
  26,
  1,
  305,
  84,
  59,
  '[{"cluster":"Pragmatic Moderates","support":32},{"cluster":"Civic Reformers","support":26},{"cluster":"Local Organizers","support":23},{"cluster":"Institutional Skeptics","support":19}]'::jsonb,
  'Pragmatic Moderates',
  'Elena',
  'Preventive credits could help, but they may fail if clinics still cannot add appointments. Pairing the credit with provider capacity targets might create more durable agreement.',
  'Active debate'
),
(
  'issue-3',
  'Should public schools require AI literacy units before high school graduation?',
  'Teachers are seeing students use AI tools long before schools have clear guidance for research, plagiarism, and responsible use. A required literacy unit could set a baseline for both opportunity and risk.',
  'r/educationpolicy',
  'Education',
  'Priya',
  'Georgia',
  156,
  38,
  1,
  351,
  79,
  54,
  '[{"cluster":"Local Organizers","support":31},{"cluster":"Civic Reformers","support":25},{"cluster":"Pragmatic Moderates","support":24},{"cluster":"Institutional Skeptics","support":20}]'::jsonb,
  'Institutional Skeptics',
  'Marcus',
  'AI literacy is necessary, but adding a graduation requirement without teacher support may widen district gaps. A phased pilot with shared curriculum could bridge more people first.',
  'Policy watch'
),
(
  'issue-4',
  'How aggressive should the U.S. be about carbon reporting requirements for large manufacturers?',
  'Manufacturers say new reporting rules could be expensive in the short term, while climate advocates argue that transparent data is necessary before stronger emissions policy can work. The question is how fast regulators should move.',
  'r/climatepolicy',
  'Climate',
  'Luis',
  'Arizona',
  119,
  31,
  1,
  268,
  73,
  49,
  '[{"cluster":"Civic Reformers","support":35},{"cluster":"Pragmatic Moderates","support":28},{"cluster":"Institutional Skeptics","support":21},{"cluster":"Local Organizers","support":16}]'::jsonb,
  'Pragmatic Moderates',
  'Tessa',
  'Reporting can be valuable, but manufacturers are more likely to support it if compliance phases in by sector and if smaller suppliers get shared tooling instead of one-size-fits-all rules.',
  'Active debate'
);

insert into public.issue_comments (id, issue_id, author, cluster, stance, body) values
(
  'comment-1',
  'issue-1',
  'Ari',
  'Pragmatic Moderates',
  'against',
  'Publishing the dashboard only helps if the affordability definitions are consistent across cities; otherwise everyone argues over the numbers instead of the policy.'
),
(
  'comment-2',
  'issue-1',
  'Nia',
  'Local Organizers',
  'for',
  'I support the dashboard idea because local tenants need something they can point to at hearings, not just campaign promises.'
),
(
  'comment-3',
  'issue-2',
  'Elena',
  'Pragmatic Moderates',
  'against',
  'Credits sound strong on paper, but appointment supply is still a bottleneck. Without more provider capacity, people may have coverage and still wait too long.'
),
(
  'comment-4',
  'issue-3',
  'Marcus',
  'Institutional Skeptics',
  'against',
  'I agree with the goal, but districts will need ready-to-use curriculum or this turns into another mandate that widens quality gaps.'
),
(
  'comment-5',
  'issue-4',
  'Tessa',
  'Pragmatic Moderates',
  'for',
  'Manufacturers are more likely to cooperate if reporting phases in by sector and smaller suppliers get shared tools.'
)
on conflict (id) do nothing;
